export const BG_PROMPTS = [
	'Blood red mist swirling in a dark forest',
	'Moonlit graveyard with crooked tombstones',
	'Haunted house surrounded by thick fog',
	'Ghostly figures floating in a dark hallway',
	'Abandoned asylum with broken windows and chains',
	'Sinister forest with glowing red eyes in the shadows',
	'Creepy abandoned mansion under a blood moon',
	'Dark cave with eerie green mist and glowing skulls',
	'Foggy cemetery with iron gates and twisted trees',
	'Lightning storm over a haunted castle on a hill',
	'Spooky pumpkin patch with flickering lanterns',
	'Creepy dungeon with blood stained walls',
	'Dark alley with mysterious shadows and glowing eyes',
	'Sinister swamp with bubbling green ooze',
	'Abandoned carnival with broken rides and eerie music',
	'Witches lair with cauldrons and glowing potions',
	'Overgrown graveyard with crumbling statues',
	'Nightmarish forest with dead trees and glowing fog',
	'Blood splattered walls in an abandoned house',
	'Dark woods with glowing ghostly apparitions',
	'Underground crypt with flickering torches',
	'Mysterious portal glowing in the center of a forest',
	'Foggy cliffside with a dark sea below',
	'Haunted corridor with eerie whispers and cold mist',
	'Dark chapel with blood red stained glass windows',
	'Rotting shipwreck on a dark stormy beach',
	'Eerie castle surrounded by thunder and lightning',
	'Shadowy underworld with glowing lava rivers',
	'Abandoned mine shaft with broken lanterns and bones',
	'Sinister forest path under a blood moon'
]

export const MASK_PROMPTS = [
	'Vampire fangs with glowing red eyes',
	'Full Jack o lantern with fiery eyes and jagged grin',
	'Zombie decayed face with hollow eyes and torn lips',
	'Giant bat wings covering face with glowing eyes',
	'Skull mask with empty eyes and cracked jaw',
	'Full witch s face with glowing green eyes and hooked nose',
	'Spider face with multiple eyes and venomous fangs',
	'Ghostly sheet with dark empty eyes and a wide open mouth',
	'Demon s horned face with flaming eyes and sharp teeth',
	'Sinister clown mask with glowing eyes and bloody smile',
	'Crow skull covering head with glowing eyes and beak',
	'Mummy s face wrapped in bandages with stitched lips',
	'Giant cat demon face with sharp fangs and glowing eyes',
	'Full devil face with flaming red eyes and twisted grin',
	'Cyclops face with a single glowing eye and monstrous mouth',
	'Frankenstein s monster with stitched face and hollow eyes',
	'Ghoul mask with glowing eyes and rotting teeth',
	'Reaper s skull with hood and hollow eyes',
	'Haunted jack o lantern covering face with green glow',
	'Blood dripping mask with dark eyes and blood soaked teeth',
	'Full werewolf face with glowing eyes and sharp fangs',
	'Creepy doll mask with wide eyes and cracked mouth',
	'Burnt face with melted skin and empty eye sockets',
	'Alien face with large black eyes and sharp teeth',
	'Haunted scarecrow mask with glowing stitched smile',
	'Gargoyle face with stone skin and glowing eyes',
	'Pumpkin head with eerie carved eyes and mouth',
	'Full phantom face with hollow eyes and eerie grin',
	'Vampire bat mask with sharp fangs and red glowing eyes',
	'Devil s mask with glowing horns and demonic grin'
]

export const INTERVIEW_ANSWERS = [
	'I will most likely be spending my time figuring out how to turn pancakes into spaceships because breakfast should always be ready for extraterrestrial beings or hungry dragons at sunrise.',
	`I am planning on moving to the mountains to learn the ancient art of communicating with squirrels and chipmunks, then I'll sell magical nuts on a giant online platform.`,
	'In five years, I hope to be a professional time traveler who goes back to medieval times to challenge knights to jousting competitions using rubber chickens and very shiny spoons.',
	`I'll probably be teaching ghosts how to play chess in a haunted castle, while at the same time inventing a new type of bubblegum that allows people to float over traffic.`,
	'Honestly, my ultimate goal is to run a successful bakery on Mars that specializes in cupcakes shaped like spaceships, while also developing an app for teleportation using cake ingredients.',
	`I hope to be leading a team of highly trained penguins on a mission to discover new planets, where we'll open intergalactic smoothie shops run by talking cacti with sunglasses.`,
	`I see myself becoming a vampire DJ at a club for werewolves, where I'll mix spooky beats and serve drinks that glow in the dark, but only on full moons.`,
	"I'll be flying a jetpack across the world to deliver pizzas made out of stardust, all while working on my side project of teaching clouds how to dance the cha-cha.",
	'In the future, I plan to become an archaeologist who only digs up ancient roller skates and uses them to open a museum for people who love skating with dinosaurs.',
	'My career will take me to an underwater city where I will train jellyfish to code websites and create glowing neon light shows for the fish who attend our nightly tech parties.',
	`I'll be riding unicorns through the desert, looking for magic carpets to sell on my online marketplace that only accepts payment in gold doubloons or enchanted moonstones.`,
	'I see myself opening a theme park where the roller coasters are made out of spaghetti and the only way to enter is by solving riddles given by wise old turtles.',
	`In five years, I'll be launching my own line of sunglasses for dogs and cats, while also being the CEO of a company that builds luxury sandcastles on beaches around the world.`,
	'I will be hosting my own reality TV show where contestants have to bake pies while fighting off ninjas and performing Broadway musicals at the same time, all under the moonlight.',
	'My dream is to open a cafe in a parallel universe where the waiters are robots who serve holographic food, and every customer leaves with a free pet unicorn plushie.',
	`I'll be inventing the world's first hoverboard that doubles as a coffee maker, because what's better than flying around while also making the perfect cup of espresso every morning?`,
	`I see myself working as a professional ice sculptor on Pluto, where I'll create art that melts into ice cream, which is then delivered to customers by flying penguins on sleds.`,
	'In five years, I will be solving mysteries with my team of highly intelligent detective hamsters, who will help me unlock the secrets of the universe using cheese and secret tunnels.',
	`I plan on building a treehouse that reaches the stars, where I'll host parties for aliens, fairies, and elves, all while serving the finest galaxy-flavored tea and cupcakes.`,
	`In five years, I'll be running a ghost-hunting business with my pet dragon, who breathes glitter instead of fire, while we travel across dimensions to collect rare magical artifacts.`
]

export const INTRODUCTIONS = [
	'The fog thickens... something stirs in the dark, creating a monstrous portfolio.',
	'Deep within the shadows, your code is awakening… can you feel it?',
	'The spirits of forgotten repositories are gathering… something is emerging.',
	`A sinister force is shaping your projects… dare to face what's coming?`,
	"In the eerie silence, fragments of your code whisper their secrets… it's almost time.",
	"From the depths of GitHub's abyss, something terrifying is taking form.",
	'A shadowy figure is conjuring your repositories... brace yourself.',
	'The digital storm rages as your data is summoned from the unknown.',
	'Beware... your portfolio is being crafted in the heart of darkness.',
	'Evil algorithms are weaving a tale of your skills... it will soon be revealed.'
]

export const HALLOWEEN_FACTS = [
	`Did you know that black cats were once believed to be witches' familiars?`,
	'In some cultures, Halloween marks the night when the veil between worlds is the thinnest.',
	'The legend of Sleepy Hollow tells of a headless horseman haunting the living.',
	"Mysterious lights, known as will-o'-the-wisps, have led travelers to their doom for centuries.",
	'The Winchester Mystery House has over 160 rooms and stairs leading to nowhere.',
	'Vampires were once thought to be real, with corpses staked to prevent their return.',
	'During the Victorian era, séances were a popular way to communicate with the dead.',
	'In 1966, a strange signal from space was detected—its source is still unknown.',
	'The Tower of London is said to be haunted by the ghost of Anne Boleyn.',
	'In 1977, a British family reported being terrorized by a poltergeist in Enfield.',
	'The Bermuda Triangle has claimed the lives of over 1,000 people who vanished without a trace.',
	'On Halloween in 1938, many believed Earth was under alien attack due to a radio drama.',
	'The Mary Celeste was found abandoned at sea, its crew missing without a trace.',
	'In Salem, Massachusetts, 19 people were hanged for witchcraft in 1692.',
	'Some believe that mirrors can act as portals to other dimensions during Halloween.',
	'Crop circles continue to appear mysteriously in fields worldwide, defying explanation.',
	'In Mexico, Día de los Muertos celebrates the return of spirits to the mortal world.',
	'The Mothman, a creature with glowing red eyes, was sighted in West Virginia in 1966.',
	'The legend of Bloody Mary says her spirit can be summoned by repeating her name in a mirror.',
	"In Romania, some still believe that Dracula's castle is haunted by the undead.",
	'The Amityville Horror house is infamous for being the site of paranormal events.',
	"In 1587, a colony of settlers vanished from Roanoke Island, leaving the word 'Croatoan' carved on a tree.",
	"Jack-o'-lanterns were originally carved from turnips to ward off evil spirits.",
	'In 1947, an alleged UFO crash at Roswell sparked conspiracy theories about aliens.',
	'Some say that if you stand in front of a mirror at midnight on Halloween, you can see your future spouse.',
	"In the 1800s, people held 'Dumb Suppers,' silent meals to invite the spirits of the dead.",
	'In Ireland, Halloween was originally known as Samhain, marking the end of the harvest season.',
	'The ghost ship Flying Dutchman is said to sail the seas, never able to make port.',
	'In 1978, a meteorite struck Earth, and some believed it contained alien life forms.',
	`Some believe that hearing an owl's call is an omen of death.`
]

export const FINAL_MESSAGES = [
	'The darkness settles... and something has emerged from the shadows. Are you ready to face it?',
	'The storm has passed, but what it leaves behind may terrify you. Are you brave enough?',
	'The veil between you and the unknown is thin... and now it lifts. Are you prepared?',
	'The last piece has fallen into place... dare to see what lies beyond?',
	'The creation is complete. Do you have the courage to see it?',
	'Something terrifying has been made just for you... Are you ready to see it?',
	'The waiting is over... but what comes next may haunt you. Ready?',
	"You've come this far... now face what has been summoned. Are you ready?",
	'The code has spoken, the spirits have answered. Do you dare proceed?',
	'The final question... will you step into the unknown? Are you ready?'
]

export const USER_PATH_CLD = 'hauntedfolio/users'
