export const BG_PROMPTS = [
	'Blood red mist swirling in a dark forest',
	'Moonlit graveyard with crooked tombstones',
	'Haunted house surrounded by thick fog',
	'Ghostly figures floating in a dark hallway',
	'Abandoned asylum with broken windows and chains',
	'Sinister forest with glowing red eyes in the shadows',
	'Creepy abandoned mansion under a blood moon',
	'Dark cave with eerie green mist and glowing skulls',
	'Foggy cemetery with iron gates and twisted trees',
	'Lightning storm over a haunted castle on a hill',
	'Spooky pumpkin patch with flickering lanterns',
	'Creepy dungeon with blood stained walls',
	'Dark alley with mysterious shadows and glowing eyes',
	'Sinister swamp with bubbling green ooze',
	'Abandoned carnival with broken rides and eerie music',
	'Witches lair with cauldrons and glowing potions',
	'Overgrown graveyard with crumbling statues',
	'Nightmarish forest with dead trees and glowing fog',
	'Blood splattered walls in an abandoned house',
	'Dark woods with glowing ghostly apparitions',
	'Underground crypt with flickering torches',
	'Mysterious portal glowing in the center of a forest',
	'Foggy cliffside with a dark sea below',
	'Haunted corridor with eerie whispers and cold mist',
	'Dark chapel with blood red stained glass windows',
	'Rotting shipwreck on a dark stormy beach',
	'Eerie castle surrounded by thunder and lightning',
	'Shadowy underworld with glowing lava rivers',
	'Abandoned mine shaft with broken lanterns and bones',
	'Sinister forest path under a blood moon'
]

export const MASK_PROMPTS = [
	'Vampire fangs with glowing red eyes',
	'Full Jack o lantern with fiery eyes and jagged grin',
	'Zombie decayed face with hollow eyes and torn lips',
	'Giant bat wings covering face with glowing eyes',
	'Skull mask with empty eyes and cracked jaw',
	'Full witch s face with glowing green eyes and hooked nose',
	'Spider face with multiple eyes and venomous fangs',
	'Ghostly sheet with dark empty eyes and a wide open mouth',
	'Demon s horned face with flaming eyes and sharp teeth',
	'Sinister clown mask with glowing eyes and bloody smile',
	'Crow skull covering head with glowing eyes and beak',
	'Mummy s face wrapped in bandages with stitched lips',
	'Giant cat demon face with sharp fangs and glowing eyes',
	'Full devil face with flaming red eyes and twisted grin',
	'Cyclops face with a single glowing eye and monstrous mouth',
	'Frankenstein s monster with stitched face and hollow eyes',
	'Ghoul mask with glowing eyes and rotting teeth',
	'Reaper s skull with hood and hollow eyes',
	'Haunted jack o lantern covering face with green glow',
	'Blood dripping mask with dark eyes and blood soaked teeth',
	'Full werewolf face with glowing eyes and sharp fangs',
	'Creepy doll mask with wide eyes and cracked mouth',
	'Burnt face with melted skin and empty eye sockets',
	'Alien face with large black eyes and sharp teeth',
	'Haunted scarecrow mask with glowing stitched smile',
	'Gargoyle face with stone skin and glowing eyes',
	'Pumpkin head with eerie carved eyes and mouth',
	'Full phantom face with hollow eyes and eerie grin',
	'Vampire bat mask with sharp fangs and red glowing eyes',
	'Devil s mask with glowing horns and demonic grin'
]
